/*
 * MIT License
 *
 * Copyright (c) 2026 Nicolas JUHEL
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Package reports provides a comprehensive framework for generating, tracking, and managing
// structured audit reports that capture detailed diagnostic findings across various system components.
// It offers a robust set of data structures and utilities for organizing, storing, and retrieving
// analytical results in a standardized, human-readable format.
package reports

import (
	audsts "github.com/nabbar/auditor/pkg/data/status"
)

// Report represents a self-contained audit report that encapsulates diagnostic findings
// from a specific component or system area. It serves as the primary data structure for
// tracking and managing analytical results throughout their lifecycle.
type Report struct {
	// Name is a unique identifier that clearly describes the report's origin, purpose, or scope.
	// It should be descriptive enough to enable easy categorization and cross-referencing
	// of different report types within the audit system. This field is used as a key identifier
	// for report tracking and management.
	Name string

	// Content contains the detailed, human-readable results of the diagnostic analysis.
	// It is typically generated by diagnostic components and may include:
	// - Summary of findings
	// - Technical analysis
	// - Recommendations for improvement
	// - Severity indicators
	// The content is stored in Markdown format to enable easy rendering and visualization.
	Content string

	// Status tracks the current processing state of the report, indicating whether it is
	// pending, completed, or encountered an error. This field enables real-time monitoring
	// and management of the audit workflow, ensuring that reports are properly tracked
	// throughout their processing stages.
	Status audsts.Status
}
