/*
 * MIT License
 *
 * Copyright (c) 2026 Nicolas JUHEL
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package step3

import (
	"fmt"

	audpkg "github.com/nabbar/auditor/pkg"
	spfcbr "github.com/spf13/cobra"
)

const (
	cmdName  = "step3"
	cmdShort = "Execute a cumulative, LLM-powered audit assessment and final code validation"
	cmdLong  = `
Execute a comprehensive, cumulative audit assessment and final code validation.

  The 'step3' command serves as the final, critical analytical phase in the auditor 
  toolchain. It is designed to be executed only after the codebase has been scanned 
  ('step1' / 'scan') to generate Abstract Syntax Trees (AST) and structurally analyzed 
  ('step2' / 'analyze') to map semantic dependencies and summarize individual entries. 
  
  While 'step2' focuses on understanding what the code does at a granular, 
  architectural level, 'step3' shifts the focus entirely to evaluating how well the 
  code performs against industry standards. It leverages the semantic knowledge base 
  built during the previous steps to conduct a cumulative, high-level assessment.

  The execution of this command involves a rigorous, prompt-driven evaluation of the 
  codebase across four default primary dimensions:
  
  - Security Vulnerability Detection: The engine utilizes the LLM to identify potential 
    attack vectors, insecure cryptographic patterns, improper input sanitization, and 
    common anti-patterns (such as OWASP Top 10 vulnerabilities).
  - Performance Profiling: The audit assesses algorithmic complexity (Big O notation), 
    identifies potential bottlenecks, highlights inefficient memory management, and 
    flags resource-intensive operations that could degrade production performance.
  - Robustness and Resilience: The LLM evaluates error handling strategies, checks for 
    unhandled edge cases, and determines the overall resilience of the code under 
    unexpected failure conditions or malformed inputs.
  - Optimization and Evolution: The assessment targets both technical optimization and 
    business logic evolution. The LLM suggests strategic refactoring opportunities, 
    architectural modernization, and domain-driven enhancements, ensuring the software 
    runs efficiently at a technical level while remaining highly adaptable to future 
    business requirements.

  To achieve this, the command first re-verifies the semantic dependency graphs and 
  inter-package reference maps. Once the foundational context is established, it 
  orchestrates an asynchronous, multi-threaded dispatch of highly specialized prompts 
  to the configured LLM. The resulting findings are then aggregated into a cumulative 
  assessment, representing the final validation of the overall codebase health.

Prerequisites:
  Before invoking the 'step3' command, the user must strictly adhere to the operational 
  workflow of the auditor toolset. 
  
  First, the source code must have been successfully processed by the scanning engine 
  ('step1'). Second, the structural deep audit ('step2') must have been completed to 
  populate the semantic data models.
  
  The integrity of the internal SQLite database is rigorously enforced during the 
  pre-run validation phase. The command mandates that the internal database must contain 
  at least one fully initialized module, at least one parsed package, and at least one 
  distinct code entry. Furthermore, these entries should theoretically hold the semantic 
  metadata generated by 'step2'. If these fundamental database requirements are not met, 
  the command will immediately abort its execution, preventing the generation of empty 
  or mathematically invalid cumulative reports.

Supported Programming Languages:
  The cumulative assessment relies on the robust polyglot capabilities defined within 
  the internal 'ast' package. The specific language context drastically alters the 
  nature of the security and performance audits. The currently supported programming 
  languages include:

  - Assembler ("asm"): Audits focus on low-level buffer overflows, register mismanagement, 
    and direct memory manipulation vulnerabilities.
  - C ("c"): Assessments heavily target manual memory management (malloc/free), pointer 
    arithmetic errors, and traditional buffer overruns.
  - C++ ("cpp"): The audit encompasses C-style memory issues while adding checks for 
    object slicing, virtual table hijacking, and template metaprogramming bloat.
  - Go ("go"): Evaluations are optimized for detecting race conditions in goroutines, 
    channel deadlocks, and improper use of the 'unsafe' package.
  - Rust ("rust"): While Rust is memory-safe by default, the audit focuses on logical 
    errors, improper use of 'unsafe' blocks, and complex lifetime mismanagement.
  - Python ("python"): Assessments target dynamic typing vulnerabilities, unsafe 
    deserialization (pickle), and performance bottlenecks inherent to the GIL.
  - Java ("java"): Audits focus on Object-Oriented anti-patterns, garbage collection 
    thrashing, and framework-specific vulnerabilities (e.g., Spring misconfigurations).
  - PHP ("php"): The evaluation specifically targets web-centric flaws like SQL 
    Injection, Cross-Site Scripting (XSS), and insecure file inclusions.
  - JavaScript ("js"): Audits cover asynchronous execution flaws (promise leaks), 
    prototype pollution, and event-loop blocking operations.

Code Abstraction Types:
  The internal 'types' package classifies scanned elements into enumerated "CodeType" 
  structures. The audit assessment dynamically adjusts its focus based on these types:

  - "function" (FUNCTION): The audit scrutinizes execution flow, input validation, 
    and algorithmic efficiency.
  - "struct" (STRUCT): The assessment evaluates data layout, cohesion, and potential 
    memory alignment optimizations.
  - "interface" (INTERFACE): The LLM reviews the clarity of the contract and adherence 
    to interface segregation principles.
  - "primitive" (PRIMITIVE) and "custom" (CUSTOM): The audit assesses the domain-specific 
    usage and potential aliasing vulnerabilities of these types.

Supported LLM providers:
  The 'step3' command utilizes the same 'apitype' abstraction layer as 'step2', 
  allowing integration with major AI vendors. You must specify one of the following 
  in your configuration:

  - "OpenAI": Provides highly accurate assessments using models like GPT-4, ideal for 
    complex vulnerability detection.
  - "Anthropic": Utilizes the Claude family, excelling at analyzing massive code 
    contexts to find deeply hidden architectural flaws.
  - "Gemini": Google's models, offering fast inference for general code quality checks.
  - "Mistral": Cost-effective and performant models for broad codebase sweeps.
  - "Ollama": Essential for high-security, air-gapped environments, ensuring that 
    sensitive vulnerability data never leaves the local network.
  - "Copilot": Integrates with GitHub's infrastructure for developer-centric audits.

Configuration Architecture:
  The auditing process is entirely governed by the cascading configuration file located 
  at "<working folder>/.auditor/llmconfig.json". This JSON file strictly controls 
  API endpoints, authentication, and critical token consumption limits.

  The system uses a three-tier inheritance hierarchy:
  
  Tier 1: Global Default ("default"). The baseline behavior for all API calls.
  Tier 2: Language Overrides ("lang"). Allows provider/limit overrides based on the 
          specific language being audited (e.g., using a stronger model for C/C++ 
          security checks).
  Tier 3: Code Type Overrides ("types"). Provides granular control, allowing specific 
          settings for "functions" versus "structs".

  json schema definitions:

  1. API Definition Object ("api"):
     - "hostname": (string) FQDN or IP:Port of the API (e.g., "api.openai.com:443").
     - "model": (string) Target model identifier (e.g., "gpt-4-turbo", "llama3").
     - "timeout": (int) Max HTTP client wait time in seconds.
     - "options": (map) Key-value pairs for proprietary API flags.

  2. Authentication Object ("auth"):
     - "basic": Requires "username" and "password" strings.
     - "api": Requires an "api-key" string (Bearer token).
     - "oauth": Requires "login-uri", "timeout-login", "client-id", "secret-id", 
       and "grant-type" for enterprise token negotiation.

  3. Limitation and Quota Object ("limit"):
     - "maxToken": (int) Maximum length of the generated audit report.
     - "temperature": (float) Controls AI determinism (0.0 to 1.0). For 'step3', a 
       value close to 0.0 is critical to ensure factual vulnerability reporting and 
       prevent false positives (hallucinations).
     - "max-request-second": (int) Throttles concurrent requests to prevent HTTP 429 
       errors from the provider.
     - "max-request-token-hour" / "max-response-token-hour": (int) Hourly token 
       budgets to prevent catastrophic billing overruns.

Custom Audit Templates:
  The true power of the 'step3' command lies in its prompt-driven architecture. 
  Unlike rigid static analysis tools, this auditor evaluates code based on custom 
  templates located in the "<working folder>/.auditor/report/" (or equivalent audit) 
  directory. 
  
  Administrators can rewrite these templates to entirely alter the focus of the audit. 
  For example, you can create a template strictly focused on PCI-DSS compliance, or 
  one that only looks for specific memory leaks in C++ code. The engine injects the 
  raw code and semantic metadata into these templates before dispatching them to the LLM.

Troubleshooting and Execution Behavior:
  During execution, 'step3' will output progress logs regarding dependency resolution 
  and the cumulative audit phase. The process is asynchronous; individual LLM request 
  failures are queued for retry using exponential back-off algorithms.
  
  If execution stalls, ensure your "max-request-second" limit aligns with your 
  provider's tier. If the final audit reports are inconsistent or contain bizarre 
  recommendations, immediately lower the "temperature" setting in your "limit" block 
  to force deterministic, analytical responses from the LLM.

`
	cmdUsage   = ""
	cmdExample = ""
)

func InitCmd() *spfcbr.Command {
	cmd := audpkg.GetCobra().NewCommand(cmdName, cmdShort, cmdLong, cmdUsage, cmdExample)
	cmd.Args = spfcbr.NoArgs
	cmd.PreRunE = preRun
	cmd.RunE = run
	cmd.DisableFlagsInUseLine = true
	cmd.SilenceErrors = true

	cmd.Aliases = []string{"audit"}

	return cmd
}

func preRun(_ *spfcbr.Command, _ []string) error {
	if audpkg.GetDBManager().ModLen() < 1 {
		return fmt.Errorf("scanning files result no modules")
	} else if audpkg.GetDBManager().PkgLen() < 1 {
		return fmt.Errorf("scanning files result no packages")
	} else if audpkg.GetDBManager().EntLen() < 1 {
		return fmt.Errorf("scanning files result no entries")
	}

	return nil
}

func run(_ *spfcbr.Command, _ []string) error {
	audpkg.GetUIManager().Info("⛓️ Resolving Semantic Dependency Graphs & Inter-Package Reference Maps...")
	if e := audpkg.GetEngine().ReOrder(); e != nil {
		return fmt.Errorf("error trigger on Resolving Semantic Dependency Graphs: %w", e)
	}

	audpkg.GetDBManager().Info("🔒 Cumulative Audit Assessment & Final Validation...")
	if e := audpkg.GetEngine().Review(); e != nil {
		return fmt.Errorf("error trigger on Reviewing Audit: %w", e)
	}

	return nil
}
